name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: go-vet
        run: go vet ./...
      - name: go-fmt
        run: FMT=`go fmt ./...` && [ -z "$FMT" ]
      - name: install-golint
        run: go get -u golang.org/x/lint/golint
      - name: golint
        run: golint ./... 
      - name: build
        run: go build ./...
      - name: apt-update
        run: sudo apt update
      - name: install-test-dependencies
        run: sudo apt install -y live-build livecd-rootfs snapd fdisk gdisk qemu-system-aarch64 qemu-user-static
      - name: test
        run: sudo go test -timeout 0 -v -race -coverprofile=coverage.out -covermode=atomic ./...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
